opsMonitor/monitor/urls.py
from django.contrib import admin
from django.urls import path
from .views import monitor_items, alerts_items,alerts_flower,alerts_detail

urlpatterns = [
    path('items/',monitor_items, name='monitor_itmes_url'),
    path('alerts/', alerts_items, name='monitor_alerts_url'),
    path('alerts_detail/<int:alert_id>', alerts_detail, name='monitor_alerts_detail_url'),
    path('flower/', alerts_flower, name='monitor_flower_url')
]

opsMonitor/opsMonitor/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, login_view, logout_view,test_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login_view, name='login_url'),
    path('test_url/', test_url, name='test_url'),
    path('logout/', logout_view, name='logout_url'),
    path('index/',index, name='index_url'),
    path('monitor/', include('monitor.urls'))
]

opsMonitor/monitor/models.py
from django.db import models
from assets.models import Assets, Component
# Create your models here.


class MonitorTools(models.Model):
    send_tools_choice = (
        ('dingding','钉钉'),
        ('email','邮箱'),
    )
    name = models.CharField(verbose_name='名称',max_length=10)
    tool_name = models.CharField(choices=send_tools_choice, verbose_name='工具名称', max_length=10, default='dingding')
    tool_url = models.TextField(verbose_name='工具地址')

    class Meta:
        verbose_name = '监控工具'
        verbose_name_plural = "监控工具"


    def __str__(self):
        return self.name


class MonitorTemplates(models.Model):
    name = models.CharField(verbose_name='监控模板名称', max_length=64)
    m_time = models.IntegerField(verbose_name='监控触发时间间隔',default=30)
    send_tools = models.ForeignKey(MonitorTools, verbose_name='发送工具', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '监控模板'
        verbose_name_plural = "监控模板"

    def __str__(self):
        return self.name


class ComponentsAssets(models.Model):
    env_type_choice = (
        ('dev','开发'),
        ('test','测试'),
        ('pre','预生产'),
        ('prod','生产'),
    )

    component = models.ForeignKey(Component,verbose_name='组件', on_delete=models.CASCADE)
    env = models.CharField(choices=env_type_choice, max_length=10, null=True, blank=True, verbose_name='所属环境')
    assets = models.ManyToManyField(Assets, related_name='assets_comp', verbose_name='主机')
    monitor_interface = models.TextField(verbose_name='监控接口地址', null=True, blank=True)
    http_port = models.IntegerField(verbose_name='启动端口')
    m_template = models.ForeignKey(MonitorTemplates, verbose_name='监控模板', on_delete=models.CASCADE)
    is_monitor = models.BooleanField(verbose_name='是否监控', default=False)
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = '组件事件'
        verbose_name_plural = "组件事件"
        ordering = ['-c_time']

    def __str__(self):
        return "%s-%s" % (self.env, self.component)


class MonitorTask(models.Model):
    send_status_choice = (
        ('y','发送成功'),
        ('n','发送失败'),
    )
    env_type_choice = (
        ('dev','开发'),
        ('test','测试'),
        ('pre','预生产'),
        ('prod','生产'),
    )
    env = models.CharField(choices=env_type_choice, verbose_name='环境',max_length=12)
    components_assets = models.ForeignKey(ComponentsAssets, on_delete=models.CASCADE)
    components_host = models.CharField(verbose_name='告警主机', max_length=100, null=True,blank=True)
    send_tool_templates = models.ForeignKey(MonitorTemplates, verbose_name='发送模板', on_delete=models.CASCADE)
    send_status = models.CharField(choices=send_status_choice, null=True, blank=True,verbose_name='发送状态', max_length=4)
    send_context = models.TextField(verbose_name='发送内容')
    redis_key = models.CharField(verbose_name='redis_key',max_length=200)
    recover_status = models.BooleanField(verbose_name='是否恢复', default=False)
    c_time = models.DateTimeField(verbose_name='报警时间', auto_now_add=True)
    u_time = models.DateTimeField(verbose_name='恢复时间',auto_now=True)

    class Meta:
        verbose_name = '监控结果'
        verbose_name_plural = "监控结果"
        ordering = ['-c_time']

opsMonitor/monitor/views.py
from django.shortcuts import render
from .models import ComponentsAssets, MonitorTask
from django.contrib.auth.decorators import login_required
from django.conf import settings
# Create your views here.


@login_required
def monitor_items(request):
    title1, title2, title3 = '监控事件管理', 'Items', '所有监控的Items事件'
    monitor_itmes_obj = ComponentsAssets.objects.all()
    return render(request,'monitor/items.html',locals())


@login_required
def alerts_items(request):
    title1, title2, title3 = '监控告警管理', 'Alerts', '所有监控告警'
    monitor_alerts_obj = MonitorTask.objects.all()
    return render(request,'monitor/alerts.html',locals())


@login_required
def alerts_detail(request, alert_id):
    title1, title2, title3 = '监控告警管理', 'Alerts detail', '告警详情'
    monitor_alerts_detail_obj = MonitorTask.objects.filter(id=alert_id)
    return render(request,'monitor/alerts_detail.html',locals())

@login_required
def alerts_flower(request):
    title1, title2, title3 = 'Celery进程监控', 'Flowers', 'Celery进程监控'
    url = settings.FLOWER_URL
    return render(request, 'monitor/flower.html', locals())

opsMonitor/templates/monitor/alerts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block top_title %}{{title1}}{% endblock %}
{% block link %}
<!-- DataTables -->
<!-- DataTables -->
<link rel="stylesheet" href="/static/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
{%endblock%}
{% block content%}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{title2}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index_url' %}">Home</a></li>
            <li class="breadcrumb-item active">DataTables</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">{{title3}}</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>组件名</th>
                <th>所属环境</th>
                <th>主机</th>
                <th>发送状态</th>
                <th>故障状态</th>
                <th>告警时间</th>
              </tr>
              </thead>
              <tbody>
              {% for alert in monitor_alerts_obj %}
              <tr>
                <td>{{alert.components_assets.component.name}}</td>
                <td>{{alert.env}}</td>
                <td>{{alert.components_host}}</td>
                <td>{{alert.get_send_status_display}}</td>
                <td>{% if alert.recover_status %}<button class="btn btn-xs btn-success">已恢复</button>{% else %}<button class="btn btn-xs btn-warning">未恢复</button>{% endif%}</td>
                <td>{{alert.c_time}}</td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
{%endblock%}
{% block script %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock%}

opsMonitor/templates/monitor/alerts_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block top_title %}{{title1}}{% endblock %}
{% block link %}
<!-- DataTables -->
<!-- DataTables -->
<link rel="stylesheet" href="/static/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
{%endblock%}
{% block content%}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{title2}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index_url' %}">Home</a></li>
            <li class="breadcrumb-item active">DataTables</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">{{title3}}</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            {% for alert in monitor_alerts_detail_obj %}
            <p>组件名:  <strong>{{alert.components_assets.component.name}}</strong></p>
            <p>主机: <strong>{{alert.components_host}}</strong></p>
            <p>发送工具模板: <strong>{{alert.send_tool_templates.name}}</strong></p>
            <p>消息发送状态: <strong>{{alert.get_send_status_display}}</strong></p>
            <p>redis_key: <strong>{{alert.redis_key}}</strong></p>
            <p>告警状态: {% if alert.recover_status %}<button class="btn btn-sm btn-success"><strong>已经恢复</strong></button>{%else%}<button class="btn btn-sm btn-warning"><strong>未恢复</strong></button>{%endif%}</p>
            {% if alert.recover_status %}
            <p>故障报警时间:  <strong>{{alert.c_time}}</strong></p>
            <p>故障恢复时间:  <strong>{{alert.u_time}}</strong></p>
            {% else %}
            <p>报警时间:  <strong>{{alert.c_time}}</strong></p>
            {% endif %}
            <p>故障消息: {{alert.send_context}}</p>
            {% endfor %}
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
{%endblock%}
{% block script %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock%}

opsMonitor/templates/monitor/flower.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block top_title %}{{title1}}{% endblock %}
{% block link %}
<!-- DataTables -->
<!-- DataTables -->
<link rel="stylesheet" href="/static/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
{%endblock%}
{% block content%}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{title2}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">DataTables</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-12">
<div class="main_page">
	 <iframe scrolling="no" id="main" name="main" frameborder="0"  src="{{url}}"
        style="min-height:600px;width:100%;height:100%;"></iframe>
</div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
{%endblock%}
{% block script %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>

<script>
  // 计算页面的实际高度，iframe自适应会用到
  function calcPageHeight(doc) {
      var cHeight = Math.max(doc.body.clientHeight, doc.documentElement.clientHeight)
      var sHeight = Math.max(doc.body.scrollHeight, doc.documentElement.scrollHeight)
      var height  = Math.max(cHeight, sHeight)
      return height
  }
  //根据ID获取iframe对象
  var ifr = document.getElementById('main')
  ifr.onload = function() {
  	  //解决打开高度太高的页面后再打开高度较小页面滚动条不收缩
  	  ifr.style.height='0px';
      var iDoc = ifr.contentDocument || ifr.document
      var height = calcPageHeight(iDoc)
      if(height < 850){
      	height = 850;
      }
      ifr.style.height = height + 'px'
  }
</script>
{% endblock%}

opsMonitor/templates/monitor/items.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block top_title %}{{title1}}{% endblock %}
{% block link %}
<!-- DataTables -->
<!-- DataTables -->
<link rel="stylesheet" href="/static/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
{%endblock%}
{% block content%}
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{title2}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">DataTables</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">{{title3}}</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>组件名</th>
                <th>所属环境</th>
                <th>主机</th>
                <th>启动端口</th>
                <th>接口地址</th>
                <th>告警模板</th>
                <th>是否监控</th>
                <th>创建时间</th>
              </tr>
              </thead>
              <tbody>
              {% for m_asset in monitor_itmes_obj %}
              <tr>
                <td>{{m_asset.component}}</td>
                <td>{{m_asset.get_env_display}}</td>
                <td>{%for host in m_asset.assets.all %}<li>{{host}}</li>{%endfor%}</td>
                <td>{{m_asset.http_port}}</td>
                <td>{{m_asset.monitor_interface}}</td>
                <td>{{m_asset.m_template.name}}</td>
                <td>{% if m_asset.is_monitor %}<button class="btn btn-xs btn-success">监控中</button>{% else %}<button class="btn btn-xs btn-warning">未监控</button>{% endif%}</td>
                <td>{{m_asset.c_time}}</td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
{%endblock%}
{% block script %}
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock%}